Refresh volatile FETCH corpus pins

diff --git a/corpus/migrate/docker/phpmyadmin/Cixfile b/corpus/migrate/docker/phpmyadmin/Cixfile
--- a/corpus/migrate/docker/phpmyadmin/Cixfile
+++ b/corpus/migrate/docker/phpmyadmin/Cixfile
@@ -5,7 +5,7 @@ BUILDER package3
   ENV VERSION = 5.2.3
   ENV SHA256 = 57881348297c4412f86c410547cf76b4d8a236574dd2c6b7d6a2beebe7fc44e3
   ENV URL = https://files.phpmyadmin.net/phpMyAdmin/$VERSION/phpMyAdmin-$VERSION-all-languages.tar.xz
-  FETCH bash -c 'set -eu; export GNUPGHOME="$PWD/gnupg"; mkdir -m 700 "$GNUPGHOME"; curl --fail --location --output phpMyAdmin.tar.xz "$URL"; curl --fail --location --output phpMyAdmin.tar.xz.asc "$URL.asc"; echo "$SHA256 *phpMyAdmin.tar.xz" | sha256sum -c -; curl --fail --location https://keys.openpgp.org/vks/v1/by-fingerprint/3D06A59ECE730EB71B511C17CE752F178259BD92 | gpg --batch --import; gpg --batch --verify phpMyAdmin.tar.xz.asc phpMyAdmin.tar.xz; gpgconf --kill all; rm -rf "$GNUPGHOME"' EXPECT sha256-0UThvehGmRwp33q84MI46oZv0gZMGeQ3T9xaObyPlKw=
+  FETCH bash -c 'set -eu; export GNUPGHOME="$PWD/gnupg"; mkdir -m 700 "$GNUPGHOME"; curl --fail --location --output phpMyAdmin.tar.xz "$URL"; curl --fail --location --output phpMyAdmin.tar.xz.asc "$URL.asc"; echo "$SHA256 *phpMyAdmin.tar.xz" | sha256sum -c -; curl --fail --location https://keys.openpgp.org/vks/v1/by-fingerprint/3D06A59ECE730EB71B511C17CE752F178259BD92 | gpg --batch --import; gpg --batch --verify phpMyAdmin.tar.xz.asc phpMyAdmin.tar.xz; gpgconf --kill all; rm -rf "$GNUPGHOME"'
   RUN mkdir -p output
   RUN <<BUILD
 tar -xf phpMyAdmin.tar.xz
